# Generated by Django 3.0.2 on 2020-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20200120_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='prepayment_amount',
            field=models.PositiveIntegerField(default=100, verbose_name='Сумма предоплаты'),
        ),
    ]
