# Generated by Django 3.0.2 on 2020-02-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_prepayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Сколько раз была собрана закупка'),
        ),
    ]
