# Generated by Django 3.0.2 on 2020-02-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchase_purchase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='completeness',
            field=models.FloatField(default=0, verbose_name='Процент завершения'),
        ),
    ]
