# Generated by Django 3.0.2 on 2020-02-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация пройдена'),
        ),
    ]
