# Generated by Django 3.0.2 on 2020-01-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prepayment_amount',
        ),
    ]
