# Generated by Django 3.0.2 on 2020-02-03 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20200122_1710'),
        ('orders', '0004_remove_order_prepayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart', verbose_name='Корзина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PP', 'Ожидается предоплата'), ('PM', 'Внесена предоплата'), ('PR', 'Возврат предоплаты'), ('FE', 'Ожидается внесение доплаты'), ('FP', 'Доплата внесена'), ('FX', 'Срок внесения предоплаты истек'), ('DE', 'Доставляется до офиса'), ('CL', 'Заказ закрыт')], default='PM', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
