# Generated by Django 3.0.2 on 2020-02-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_prepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'транзакция', 'verbose_name_plural': 'транзакции'},
        ),
    ]
