# Generated by Django 3.0.2 on 2020-01-09 00:31

from django.db import migrations, models
import django.utils.timezone
import dostawemo.users.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рожденя')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Улица')),
                ('house', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Дом')),
                ('corpus', models.CharField(blank=True, max_length=2, null=True, verbose_name='Корпус')),
                ('flat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартира')),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='Хобби')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/users/', verbose_name='Фото')),
                ('bonus_points', models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы')),
                ('cashback_points', models.PositiveIntegerField(default=0, verbose_name='Кэшбэк')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', dostawemo.users.models.UserManager()),
            ],
        ),
    ]
