# Generated by Django 3.0.2 on 2020-01-09 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'цвет', 'verbose_name_plural': 'цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'изображение продукта', 'verbose_name_plural': 'изображения продукта'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'размер', 'verbose_name_plural': 'размеры'},
        ),
        migrations.AlterField(
            model_name='product',
            name='archived',
            field=models.BooleanField(verbose_name='Поместить в архив'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purchases.Purchase', verbose_name='Закупка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/', verbose_name='Изображение'),
        ),
    ]
